package querySrbija;

public class QueryBillingRecordsTeles {

    //***** SAOBRACAJ ******
    public static String proba = "SELECT sum(duration) FROM billing_record.billing_records_teles_2016_01;";

    //1
    public static String ostvareniTelefonskiSaobracajOdFiksneKaFiksnimMrezama
            = "select sum(duration)/60 from(\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_01\n"
            /*     + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_02\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_03\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_04\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_05\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_06\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_07\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_08\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_09\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_10\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_11\n"
            + "union all\n"
            + "select duration, destination, dnis, peerid, direction, ani from billing_records_teles_2016_12\n" */
            + ") as foo\n"
            + "where destination \n"
            + "not like '%mob%'\n"
            + "and destination not like '%kratki%'\n"
            + "and dnis not rlike '381[7-9].*'\n"
            + "and direction ='E' and peerid ='2';";

    // 2 (2.1 + 2.2 + 2.3)
    public Double ostvareniTelefonskiSaobracaj_Od_Fiksne_Ka_Drugim_Domacim_Fiksnim_Mrezama;
    //2.1
    public static String ostvareniTelefonskiSaobracaj_Od_Fiksne_Ka_Drugim_Domacim_Fiksnim_Mrezama_Telekom_Srbija
            = "select sum(duration)/60 from(\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_01\n"
            /*    + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_02\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_03\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_04\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_05\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_06\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_07\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_08\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_09\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_10\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_11\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_12\n" */
            + ") as foo\n"
            + "where peerID ='2' and direction = 'E' and category = 'fiksna TS';";

    //2.2
    public static String ostvareniTelefonskiSaobracaj_Od_Fiksne_Ka_Drugim_Domacim_Fiksnim_Mrezama_SBB
            = "select sum(duration)/60 from(\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_01\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_02\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_03\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_04\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_05\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_06\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_07\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_08\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_09\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_10\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_11\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_12\n"
            + ") as foo\n"
            + "where peerID ='2' and direction = 'E' and category = 'fiksna SBB';";

    //2.3
    public static String ostvareniTelefonskiSaobracaj_Od_Fiksne_Ka_Drugim_Domacim_Fiksnim_Mrezama_ORION
            = "select sum(duration)/60 from(\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_01\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_02\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_03\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_04\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_05\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_06\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_07\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_08\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_09\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_10\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_11\n"
            + "union all\n"
            + "select duration, destination, category, direction, peerid from billing_records_teles_2016_12\n"
            + ") as foo\n"
            + "where peerID ='2' and direction = 'E' and category = 'fiksna ORION';";
    //3 (3.1 + 3.2)
    public static String ostvareniTelefonskiSaobracaj_od_Fiksne_Ka_Mobilnim_Mrezama
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, destination from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where destination like '%mob%';";

    //3.1
    public static String ostvareniTelefonskiSaobracaj_od_Fiksne_Ka_Mobilnim_Mrezama_Ka_Domacim_Operatorima
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, destination from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where destination like 'Srbija-mob%';";

    //3.2
    public static String ostvareniTelefonskiSaobracaj_od_Fiksne_Ka_Mobilnim_Mrezama_Ka_Inostranim_Operatorima
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, destination from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, destination from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where destination not like 'Srbija-mob%' and destination like '%mob%';";
    //***
    //4 (4.1 + 4.2 + 4.3)
    public static String ostvareni_telefonski_saobracaj_ka_negeografskim_i_kratkim_kodovima;
    //***
    //4.1 (4.1.1 + 4.1.2)
    public String VASservisi;
    //4.1.1
    public static String kod09xx
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo \n"
            + "where dnis like '3819%';";

    //4.1.2
    public static String kod0780
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo \n"
            + "where dnis like '38178%'; ";
    //***
    //4.2 
    public static Double kratki_kodovi;
    //***
    //4.2.1
    public static String hitne_sluzbe
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	dnis = '38111112' or\n"
            + "    dnis = '38111192' or\n"
            + "    dnis = '38111193' or\n"
            + "    dnis = '38111194' or\n"
            + "    dnis = '381111976';";
//4.2.2
    public static String usluge_od_javnog_interesa
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "     dnis = '381111985' or\n"
            + "    dnis = '381111987' or\n"
            + "    dnis = '3811119191' or\n"
            + "    dnis = '3811119860';";
    //4.2.3
    public static String komercijalne_usluge
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	dnis = '38111195' or\n"
            + "    dnis = '3811111811' or\n"
            + "    dnis = '3811119771' or\n"
            + "    dnis = '3811119812' or\n"
            + "    dnis = '3811119811';";

    //4.3
    public static Double ostale_negeografske_usluge;

    //4.3.1
    public static String freephone
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	dnis like '381800%'";
    //4.3.2
    public static String univPristupBroju
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	dnis like '38170%';";

    //4.3.3
    public static String saobracaj_ka_VoIP_operatoru;

    //4.3.4
    public static String M2M
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	dnis like '3817%';";

    //4.3.5
    public static String nomadskaUsluga
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	dnis like '38172%' or\n"
            + "    dnis like '3817%';";
    //5 (6+9)
    public static String ukupan_medjunarodni_telefonski_saobracaj;

    //6 (7+8)
    public static String medjunarodni_odlazni_telefonski_saobracaj_iz_fiksne_mreze;

    //7
    public static String evropa
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	(dnis like '4%' or\n"
            + "    dnis like '3%'\n)"
            + "    and dnis not like '381%';";

    //8
    public static String ostatak_sveta
            = "select sum(duration)/60 from(\n"
            + "SELECT duration, dnis from billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, dnis from billing_records_teles_2016_12\n"
            + "\n"
            + ") as foo where\n"
            + "	dnis not like '4%' and\n"
            + "    dnis not like '3%'\n";

    //9 - rucno unosimo iz usaglasenih podataka
    public static String medjunarodni_dolazni_telefonski_saobracaj_ka_fiksnoj_mrezi;

    //10 - vrednost 0
    public static Double broj_medjunarodnih_telegrama;

    //11 
    public static String prosecna_duzina_razgovora_u_mrezi
            = "select (sum(duration)/60)/count(duration) from(\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, peerid, origsiteid, termsiteid FROM billing_record.billing_records_teles_2016_12\n"
            + ")as foo\n"
            + "where peerid=2 and origSiteId='ikom.detel.rs' and termsiteid='ikom.detel.rs' and duration > 0;";

    //12 
    public static String prosecna_duzina_razgovora_ka_mobilnim_mrezema
            = "select (sum(duration)/60)/count(duration) from(\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, peerid, destination, direction FROM billing_record.billing_records_teles_2016_12\n"
            + ")as foo\n"
            + "where peerid=2 and destination like '%mob%' and direction ='E';";

    //13
    public static String prosecna_duzina_razgovora_ka_inostranstvu
            = "select (sum(duration)/60)/count(duration) from(\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, peerid, dnis, direction FROM billing_record.billing_records_teles_2016_12\n"
            + ")as foo\n"
            + "where peerid=2 and dnis not like '381%' and direction ='E';";

    //14
    public static Double VoIP_minuti;

    //15
    public static String ostvareni_telefonski_saobracaj_u_okviru_sopstvene_mreze
            = "SELECT sum(duration)/60 FROM (\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction FROM billing_records_teles_2016_12\n"
            + ") as foo\n"
            + "where peerid=2 and origSiteId='ikom.detel.rs' and termsiteid='ikom.detel.rs' and direction='E';";

    //15.1
    public static Double ka_geografskim_kodovima;
    //15.4.1
    public static String freephoneOduzimanje
            = "SELECT sum(duration)/60 FROM (\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, direction, termSiteId, dnis FROM billing_records_teles_2016_12\n"
            + ") as foo\n"
            + "where direction ='I' \n"
            + "and termSiteId ='ikom.detel.rs' \n"
            + "and dnis like '3818%';";

    //***** TERMINACIJA SAOBRACAJA *****
    //1 (1.1 + 1.2 + 1.3)
    public String ostvareni_dolazni_nacionalni_telefonski_saobracaj_iz_drugih_mreza_termincija;
    //1.1 (1.1.1 + ... + 1.1.10)
    public String ostvareni_dolazni_nacionalni_telefonski_saobracaj_iz_fiksnih_mreza;
    //1.1.1 (1.1.1.1 + ... + 1.1.1.6)
    public static String terminacija_iz_drugih_fiksnih_TS
            = "SELECT sum(duration)/60 FROM (\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_01\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_02\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_03\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_04\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_05\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_06\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_07\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_08\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_09\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_10\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_11\n"
            + "union all\n"
            + "SELECT duration, peerid, origSiteId, termsiteid, direction, ani, dnis FROM billing_records_teles_2016_12\n"
            + ") as foo\n"
            + "where termsiteid='ikom.detel.rs' \n"
            + "and direction='I'\n"
            + "and origSiteId not like 'ikom.detel.rs' \n"
            + "and ani like '381%'\n"
            + "and ani not like '3816%'\n"
            + "and dnis not like '3818%'";
    //2.1 uzeti iz RVC IKOM - JOTEL
    //2.2 uzeti iz usaglaseni podaci

}
